name: ron
version: '0.1'
copyright: 2018 Yuriy Syrovetskiy
license: BSD3

default-extensions:
  - StrictData

library:
  dependencies:
    - attoparsec
    - base
    - binary
    - bytestring
    - deepseq
    - flat
    - time
  exposed-modules:
    - RON.Base64
    - RON.Binary
    - RON.Binary.Parse
    - RON.Binary.Serialize
    - RON.Binary.Types
    - RON.Event
    - RON.Internal.Prelude
    - RON.Text
    - RON.Text.Parse
    - RON.Text.Serialize
    - RON.Types
    - RON.UUID
  other-modules:
    - Attoparsec.Extra
  source-dirs: lib

tests:
  test:
    dependencies:
      # global
        - base
        - bytestring
        - directory
        - hedgehog
        - tasty-hedgehog
        - tasty-th
        - time
      # package
        - ron
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: Main
    other-modules:
      - Gen
      - HexDump
    source-dirs: test

benchmarks:
  bench:
    dependencies:
      # global
        - base
        - criterion
        - deepseq
      # package
        - ron
    main: Main
    source-dirs: bench
