name: ron
version: '0.1'
copyright: 2018 Yuriy Syrovetskiy
license: BSD3

default-extensions:
  - StrictData

library:
  dependencies:
    - aeson
    - attoparsec
    - base
    - binary
    - bytestring
    - containers
    - deepseq
    - Diff
    - errors
    - extra
    - flat
    - hashable
    - mtl
    - safe
    - stringsearch
    - syb
    - template-haskell
    - text
    - time
    - unordered-containers
    - vector
  exposed-modules:
    - RON.Base64
    - RON.Binary
    - RON.Binary.Parse
    - RON.Binary.Serialize
    - RON.Binary.Types
    - RON.Data
    - RON.Data.Internal
    - RON.Data.LWW
    - RON.Data.ORSet
    - RON.Data.RGA
    - RON.Data.VersionVector
    - RON.Event
    - RON.Event.Simulation
    - RON.Internal.Prelude
    - RON.Internal.Word
    - RON.Schema
    - RON.Text
    - RON.Text.Common
    - RON.Text.Parse
    - RON.Text.Serialize
    - RON.Text.Serialize.UUID
    - RON.Types
    - RON.UUID
  other-modules:
    - Attoparsec.Extra
  source-dirs: lib

benchmarks:
  bench:
    dependencies:
      # global
        - base
        - criterion
        - deepseq
      # package
        - ron
    main: Main
    source-dirs: bench
