name: ron
version: '0.1'
copyright: 2018 Yuriy Syrovetskiy
license: BSD3

dependencies:
  - base
  - bytestring

default-extensions:
  - StrictData

library:
  dependencies:
    - attoparsec
    - binary
    - deepseq  # TODO remove???
    - flat
    - time
  exposed-modules:
    - RON.Base64
    - RON.Binary
    - RON.Event
    - RON.Text
    - RON.Text.Parse
    - RON.Text.Serialize
    - RON.Types
    - RON.UUID
  other-modules:
    - Attoparsec.Extra
    - Internal.Prelude
  source-dirs:
    - lib
    - prelude

tests:
  test:
    dependencies:
      # global
        - deepseq
        - directory
        - hedgehog
        - tasty-hedgehog
        - tasty-th
        - time
        - typed-process
      # package
        - ron
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: Main
    other-modules:
      - Gen
      - HexDump
      - Internal.Prelude
    source-dirs:
      - prelude
      - test

benchmarks:
  bench:
    dependencies:
      # global
        - criterion
        - deepseq
      # package
        - ron
    main: Main
    source-dirs:
      - bench
      - prelude
