name: ron-test

dependencies:
  # global
    - base
    - bytestring
    - containers
    - directory
    - extra
    - filepath
    - hedgehog
    - interpolate
    - mtl
    - syb
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - tasty-th
    - text
    - time
    - unordered-containers
  # project
    - ron

ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  common:
    main: Common.hs
  test:
    main: Main
    other-modules:
      - Gen
      - HexDump
      - LwwStruct
      - LwwStruct.Types

executables:
  words:
    main: Words.hs
    dependencies:
      - text-metrics
