name: ron-test

dependencies:
  # global
    - base
    - bytestring
    - directory
    - extra
    - filepath
    - hedgehog
    - interpolate
    - tasty
    - tasty-hedgehog
    - tasty-th
    - text
    - time
  # project
    - ron

ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  # common:
  #   main: Common.hs
  test:
    main: Main
    other-modules:
      - Gen
      - HexDump
