name: ron-test

dependencies:
  # global
    - base
    - bytestring
    - directory
    - hedgehog
    - interpolate
    - tasty-hedgehog
    - tasty-th
    - text
    - time
  # project
    - ron

ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  test:
    main: Main
    other-modules:
      - Gen
      - HexDump
